version: "3.8"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: poc1-django
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - 6003:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=django-poc_db
